* Linux
  Below are the instructions for manual installation.

  There's a [[./scripts/linux-install.sh][script]] in this repository that is intended to make
  installation easier:

  #+BEGIN_SRC sh
    curl https://github.com/drcandacemakedamoore/cleanX/raw/main/scripts/linux-install.sh | sh
  #+END_SRC

  Very generally, in order to install =cleanX=, you will need these
  libraries:
  + =leptonica=
  + =tesseract=
  + =opencv=

  Usually, these can be found in software packages repository
  maintained by your chosen Linux distribution, however the names and
  packaging scheme may vary.

** Debian family (Ubuntu, Mint etc.)
*** Anaconda
    In general, this should be enough:

    #+BEGIN_SRC sh
      conda install -c conda-forge -c doctormakeda cleanx
    #+END_SRC

    However, only one version of Python is supported right now (due to
    downstream dependencies): 3.7.

*** CPython
    Using =pip= you should be able to install this by running:

    #+BEGIN_SRC sh
      sudo apt-get install -y --no-install-recommends \
           libleptonica-dev \
           tesseract-ocr-all \
           libtesseract-dev \
           python3-opencv \
           python3-pip

      pip install cleanX
    #+END_SRC

    If you also want to work with the sources, you will need =dvipng=
    package to generate documentation.

    If you want to install from source, you could instead do:

    #+BEGIN_SRC sh
      sudo apt-get install -y --no-install-recommends \
                 libleptonica-dev \
                 tesseract-ocr-all \
                 libtesseract-dev \
                 python3-opencv \
                 python3-venv \
                 python3-setuptools \
                 python3-wheel

      git clone https://github.com/drcandacemakedamoore/cleanX.git
      cd ./cleanX
      python3 -m venv ./.venv
      . ./.venv/bin/activate
      ./setup.py install
    #+END_SRC

** TODO RHEL family (CentOS, Fedora, SUSE etc.)
*** Anaconda
*** CPython
** TODO Arch Linux
*** Anaconda
*** CPython
** TODO Alpine
*** Anaconda
*** CPython
* TODO MacOS
  This will probably have to include Homebrew-related stuff
** Anaconda
** CPython
* TODO Microsoft Windows
  There are some Windows package managers, I think, Chockolate is one.
  I'd need to look into these more closely.
** Anaconda
*** Vanilla Windows
*** WLS
*** MSYS2 and derivatives (Cygwin)
** CPython
*** Vanilla Windows
*** WLS
*** MSYS2 and derivatives (Cygwin)
